name: core
description: Social network demo core interfaces and methods
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crypto: ^2.1.5

dev_dependencies:
  build_runner: ^1.10.13
  source_gen: ^0.9.10+1
  pedantic: ^1.8.0
  test: ^1.6.0
