name: api_sdk
description: A lean framework for social networks
version: 1.0.0
publish_to: none
homepage: https://github.com/kenreilly/social-network-demo

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  core: 
    path: ../core/
  path: ^1.7.0
  http_server: ^0.9.8+3
  dotenv: ^1.0.0
  postgres: ^2.1.1
  jaguar_jwt: ^2.1.6

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
